/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TrackRouteImport } from './routes/track'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/privacy': typeof PrivacyRoute
  '/track': typeof TrackRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/privacy'
    | '/track'
    | '/order/$orderNumber'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/privacy'
    | '/track'
    | '/order/$orderNumber'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/privacy'
    | '/track'
    | '/order/$orderNumber'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  PrivacyRoute: typeof PrivacyRoute
  TrackRoute: typeof TrackRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  PrivacyRoute: PrivacyRoute,
  TrackRoute: TrackRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
